### ISSUE TITLE
A question of consistency...

### ISSUE THREAD

**Issue by ssteinerx** [samuel/kokki#1]
Being as there is a nice AttributeDictionary class, which masks the dict() based storage of things by coercing attribute access to properly pull things from the underlying dict(), why is the much uglier form of thing["attribute"]["otherattribute"]["ad"]["nauseum"] used in the code at all?

The inconsistency of use led to much head scratching until I had dug further into the code and found AttributeDictionary.

I'm still not sure whether AttributeDictionary is consistently used throughout the product, but if not, this would be a vast improvement over the mixed usages that obscure the intent of the code by exposing the multi-dimensional dict() based storage in some places while making them appear to be attributed objects in others.

S

**Comment by samuel** [comment]
The dictionary access is older code. I just never got around to going through and updating everything. I agree that it would good to be consistent.

**Comment by ssteinerx** [comment]
Hey, did you get my e-mail about the tutorial?  This is one of the things I had to figure out...
  S
