### ISSUE TITLE
The cookbooks seem to be almost direct translations of the Chef equivalents (e.g. nginx is almost identical)

### ISSUE THREAD

**Issue by ssteinerx** [samuel/kokki#2]
Is there a converter of some sort or was all this done by hand?

A converter (at least for the json part) would be fairly trivial as it seems that Chef generates the ruby code from the json config.

S

**Comment by samuel** [comment]
Yeah, most of the recipes are essentially rewrites of the Chef ones. It was all done by hand, and I'm not sure it's really worth the effort to try to automate it. The ideas are similar, but there's quite a few of differences between Chef and Kokki that would it difficult.

**Comment by ssteinerx** [comment]
Just for the record, Chef generates the Json config from the Ruby code, not the other way around.
